# Generated by Django 3.2.5 on 2021-07-25 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=256, null=True)),
                ('phone_number', models.CharField(max_length=45, null=True, unique=True)),
                ('kakao_id', models.CharField(max_length=45, null=True)),
                ('name', models.CharField(max_length=45, null=True)),
                ('card_company', models.CharField(max_length=45, null=True)),
                ('card_number', models.CharField(max_length=45, null=True)),
                ('bank_name', models.CharField(max_length=45, null=True)),
                ('bank_account', models.CharField(max_length=128, null=True)),
                ('address', models.CharField(max_length=128, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
