# Generated by Django 3.2.5 on 2021-07-20 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='buying_bid',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buying_bid', to='orders.bidding'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='selling_bid',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selling_bid', to='orders.bidding'),
        ),
    ]
