# Generated by Django 3.2.5 on 2021-07-21 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210720_0928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bidding',
            old_name='bid_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='status_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='contract',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
