# Generated by Django 3.2.5 on 2021-07-21 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name_english',
            new_name='name',
        ),
        migrations.AlterModelTable(
            name='productcolor',
            table='products_colors',
        ),
        migrations.AlterModelTable(
            name='producttheme',
            table='products_themes',
        ),
    ]
